name: Update Pull Request Description
description: Easily update a pull requests description

inputs:
  token:
    description: A GitHub access token
    required: true

runs:
  using: 'node16'
  main: dist/index.js

branding:
  icon: git-pull-request
  color: red