name: allset-git-actions
description: AllSet web app's git actions

inputs:
  GITHUB_TOKEN:
    required: true
  CHECK:
    required: true

runs:
  using: 'node16'
  main: dist/index.js

branding:
  icon: git-pull-request
  color: red